services:
  db:
    image: postgres:latest
    container_name: bet_tracking_postgres
    environment:
      POSTGRES_DB: betting_history_web
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: strong_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
