services:
  db:
    image: postgres:latest
    container_name: bet_tracking_postgres
    environment:
      POSTGRES_DB: betting_history_web
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: strong_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: >
      bash -c "echo \"shared_preload_libraries='pg_stat_statements'\" >> /var/lib/postgresql/data/postgresql.conf &&
                echo \"pg_stat_statements.track=all\" >> /var/lib/postgresql/data/postgresql.conf &&
                docker-entrypoint.sh postgres"

  pghero:
    image: ankane/pghero
    container_name: bet_tracking_pghero
    environment:
      DATABASE_URL: postgres://local_user:strong_password@db:5432/betting_history_web
      PGHERO_SLOW_QUERY_THRESHOLD: 100  # Set threshold to 100 milliseconds
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
