"""Add first indexes to bets

Revision ID: 642e3262e2e9
Revises: c14127e63351
Create Date: 2024-10-04 11:44:50.286894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642e3262e2e9'
down_revision = 'c14127e63351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.create_index('idx_event_date_capper_account', ['event_date', 'capper', 'account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.drop_index('idx_event_date_capper_account')

    # ### end Alembic commands ###
